before_deploy: 
  - "git config --local user.name \"Jeferson Cruz\""
  - "git config --local user.email \"jeferson_oc@live.com\""
  - "git tag \"$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)\""
deploy: 
  user: "JefersonOC"
  password: "hikCcfDokwHnXAikJL6rvgXRotvLyDdX1ZyPv5gzWrzBZ9UqGwfPiLOZzd6Ops/ERss8JQSNo/FZSOMASk89kn+8doDB/Mig0cZAQDtn4u+BB4BOxnyTH9+BY8/Dqf5dHpJ1ZVTjOYeUnKHcpxSrPu+ssj5NdOcS+2Cs3vWqZHno8TVL1lDyFcx4aTsNPgNsDHLHPcyA83Jq975tViVOjjrf6wX15UloXuuRc5YsXnjTT7Pu8Bus3XdgvWCn43Ck1yOx4kzcb/bn1SFYkny/hkg2znjDcFrHz4HFacHPyBGmX6FSckG6SO0FSuuaEestub7OSHwK/2WQiHeL9P1CtRbIdbc8IEUsainh0KGyUITMwjrt+B5mH1b1dqax+9fzPMYaO2buhTL3Au/RnqeyTpj4o1Rblm75hjpYMbDwHQD5PF2gmpJR0jNscrZYNPJPbUaHx9NNg5e/ohHORnzfMkHuDhR8dtqhT0ys8MQfInLN2ZaYoaM0LNMlat4QICBn5bjfzY58umbpb7NMlUCf/QzT8cEfVO6knSalscKBAmMDSX8XSRcu5yKVOl/FumcVMqBWvsDex7VjBfDPcCxmcd7MYNbT5fv7wWpM37IHkBksiOJnGMAQyufxKQy2EOU5eN5ahs0qovjr3oB19xAujOxyUADK2ZNGbk0Zzalh/V4="
  file: "target/fiscal4j-3.1.0-RELEASE.jar"
  provider: releases
  skip_cleanup: true
  overwrite: true
jdk: oraclejdk8
language: java
script: 
  - "mvn clean install"
